In [2]:
import numpy as np

#Q1
a1 = np.random.randint(50, 100, (5,10))
print(a1)

[[72 86 64 73 86 95 92 90 59 62]
 [62 58 88 64 58 65 94 70 53 61]
 [89 88 52 80 54 85 70 73 83 97]
 [93 63 75 66 71 64 56 68 81 77]
 [75 64 88 92 59 83 81 81 75 81]]


In [4]:
#Q2
arr1 = np.array([[1, 2], [4, 5]])
arr2 = np.array([[7, 8], [10, 11]])
print(np.matmul(arr1, arr2))

[[27 30]
 [78 87]]


In [ ]:
#Q3
arr = np.array(2**np.arange(1,11))
print(arr)

[   2    4    8   16   32   64  128  256  512 1024]


In [ ]:
#Q4
X = np.array([[0,1,2,3], [4,5,6,7], [8,9,10,11]])
print('Diagonal of X: ', np.diag(X))

Diagonal of X:  [ 0  5 10]


In [ ]:
#Q5
arr = np.diagflat([1,2,3,4])
print(arr)

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


In [ ]:
#Q6
L = []
n = 1
for i in range(4):
  l = []
  for j in range(3):
    l.append(n)
    n+=1
  L.append(l)
arr = np.triu(L, -1)
print(arr)

[[ 1  2  3]
 [ 4  5  6]
 [ 0  8  9]
 [ 0  0 12]]
