In [3]:
import numpy as np
data = [1,2,3,4,5,6]
array = np.array(data)
print(array)
print(array.dtype)
print(array.shape)
print(array.ndim)

[1 2 3 4 5 6]
int64
(6,)
1


In [4]:
import numpy as np
my_arr = np.arange(10000000)
my_list = list(range(10000000))
print(len(my_arr))
print(len(my_list))

10000000
10000000


In [5]:
import numpy as np
data2 = [[1,2,3,4],[5,6,7,8]]
arr2 = np.array(data2)
print(arr2.ndim)
print(arr2.shape)

2
(2, 4)


In [8]:
a1 = np.zeros((2,3))
a2 = np.array([[1,2,3], [4,5,6]])
a3 = np.ones((2,3))
a4 = np.eye(3)
a5 = np.arange(0,10,2)
a6 = np.random.randint(0,10, (3,3))
print(a1)
print(a2)
print(a3)
print(a4)
print(a5)
print(a6)

[[0. 0. 0.]
 [0. 0. 0.]]
[[1 2 3]
 [4 5 6]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[0 2 4 6 8]
[[2 1 4]
 [9 5 2]
 [3 4 7]]


In [9]:
arr = np.array([[1,2,3],[4,5,6]])
print(arr*arr)
print(arr+arr)
print(arr**3)
print(arr == arr)

[[ 1  4  9]
 [16 25 36]]
[[ 2  4  6]
 [ 8 10 12]]
[[  1   8  27]
 [ 64 125 216]]
[[ True  True  True]
 [ True  True  True]]


In [11]:
arr = np.array([[1,2,3], [4,5,6], [7,8,9]])
print(arr)
print(arr[1][2])
print(arr[1:2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
6
[[4 5 6]]


In [12]:
arr2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr2d[0][2])

3


In [23]:
# Activity 3

arr2d = np.array([[1,2,3],[4,5,6],[7,8,9]])

a1 = arr2d[:, 2:]
print(a1)

a2 = arr2d[1, 1:]
print(a2)

[[3]
 [6]
 [9]]
[5 6]


In [25]:
# Q1

import numpy as np
arr5x10 = np.random.randint(50,100,(5,10))
print(arr5x10)

[[77 90 61 81 92 99 86 91 67 67]
 [95 81 89 67 74 64 76 64 63 84]
 [58 93 67 57 96 86 93 63 95 71]
 [87 57 58 91 73 66 59 61 57 55]
 [74 55 91 84 91 55 70 63 98 91]]


In [41]:
# Q2

import numpy as np
arr = np.random.randint(50,100) + np.array(np.arange(50)*0.01)
arr = arr.reshape(5,10)
print(arr)

[[54.   54.01 54.02 54.03 54.04 54.05 54.06 54.07 54.08 54.09]
 [54.1  54.11 54.12 54.13 54.14 54.15 54.16 54.17 54.18 54.19]
 [54.2  54.21 54.22 54.23 54.24 54.25 54.26 54.27 54.28 54.29]
 [54.3  54.31 54.32 54.33 54.34 54.35 54.36 54.37 54.38 54.39]
 [54.4  54.41 54.42 54.43 54.44 54.45 54.46 54.47 54.48 54.49]]


In [46]:
# Q3

import numpy as np
l = [i for i in range(4, 100, 4)]
arr = np.array(l)
print(arr)

[ 4  8 12 16 20 24 28 32 36 40 44 48 52 56 60 64 68 72 76 80 84 88 92 96]


In [27]:
# Q4

import numpy as np
arr = np.array(2**np.arange(1,11))
print(arr)

[   2    4    8   16   32   64  128  256  512 1024]


In [47]:
# Q5

import numpy as np
l = []
for i in range(0,51,10):
  k = []
  for j in range(i,i+6):
    k.append(j)
  l.append(k)
arr = np.array(l)

print(arr[0][3:5])
print(arr[:, 2])
print(arr[2::2])
print(arr[3][3])
print(arr[4:,4:])

[3 4]
[ 2 12 22 32 42 52]
[[20 21 22 23 24 25]
 [40 41 42 43 44 45]]
33
[[44 45]
 [54 55]]
