In [1]:
#Q1

import numpy as np
rand_num = np.random.normal(90, 3, 25)
print(rand_num)

[85.12768357 92.03667006 81.3667259  86.28162843 86.97540426 90.91771263
 91.75570817 89.6434047  86.3865419  89.41553582 94.75616386 91.85239569
 91.91717918 92.86672886 95.42473669 92.59163958 91.24024151 94.14595963
 85.14530198 93.68338274 86.39760639 83.68403591 86.81079277 89.22145798
 93.39955411]


In [3]:
#Q2

import numpy as np
arr = np.linspace(0, 1, 20)
print(arr)

[0.         0.05263158 0.10526316 0.15789474 0.21052632 0.26315789
 0.31578947 0.36842105 0.42105263 0.47368421 0.52631579 0.57894737
 0.63157895 0.68421053 0.73684211 0.78947368 0.84210526 0.89473684
 0.94736842 1.        ]


In [10]:
#Q3

import numpy as np
L = []
n = 1
for i in range(5):
  l = []
  for j in range(5):
    l.append(n)
    n+=1
  L.append(l)
arr = np.array(L)
print(arr)

print('Standard deviation =', np.std(arr))
sum = np.sum(arr, axis = 0)
for i in range(5):
  print('Sum of elements in column {} ='.format(i+1), sum[i])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
Standard deviation = 7.211102550927978
Sum of elements in column 1 = 55
Sum of elements in column 2 = 60
Sum of elements in column 3 = 65
Sum of elements in column 4 = 70
Sum of elements in column 5 = 75


In [11]:
#Q4

import numpy as np
X = np.array([[0,1,2,3], [4,5,6,7], [8,9,10,11]])
print('Diagonal of X: ', np.diag(X))

Diagonal of X:  [ 0  5 10]


In [12]:
#Q5

import numpy as np
arr = np.diagflat([1,2,3,4])
print(arr)

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


In [15]:
#Q6

import numpy as np
L = []
n = 1
for i in range(4):
  l = []
  for j in range(3):
    l.append(n)
    n+=1
  L.append(l)
arr = np.triu(L, -1)
print(arr)

[[ 1  2  3]
 [ 4  5  6]
 [ 0  8  9]
 [ 0  0 12]]


In [16]:
#Q7

import numpy as np
arr = np.arange(100, 200, 10)
arr = arr.reshape(5,2)
print(arr)

[[100 110]
 [120 130]
 [140 150]
 [160 170]
 [180 190]]


In [26]:
#Q8

import numpy as np
arr = np.array([[1,2,3], [4,5,6], [7,8,9]])
k = int(input('Enter the value to check for: '))
if k in arr:
  i, j = np.where(arr == k)
  print('Specified value is present in array in {}th row and {}th column'.format(i[0]+1,j[0]+1))
else:
  print('Specified value is not present in array')

Enter the value to check for: 7
Specified value is present in array in 3th row and 1th column


In [18]:
#Q9

import numpy as np
arr = np.array([[1,2,3], [4,5,6], [7,8,9]])
t = np.trace(arr)
print('Sum of the diagonal elements of the array =', t)

Sum of the diagonal elements of the array = 15


In [20]:
#Q10

import numpy as np
arr = np.array([[10,2,3], [4,50,6], [7,8,9]])
d = np.linalg.det(arr)
print('Determinant of the matrix =', d)

Determinant of the matrix = 3078.0000000000036


In [22]:
#Q11

import numpy as np

arr1 = np.array([[83,29,19],[38,9,0],[1,2,3]])
arr2 = np.array([[7,29,98],[99,100,101],[43,82,19]])

print('Performing element-wise comparison arr1>arr2')
print(arr1>arr2)
print('Performing element-wise comparison arr1>=arr2')
print(arr1>=arr2)
print('Performing element-wise comparison arr1<arr2')
print(arr1<arr2)
print('Performing element-wise comparison arr1<=arr2')
print(arr1<=arr2)

Performing element-wise comparison arr1>arr2
[[ True False False]
 [False False False]
 [False False False]]
Performing element-wise comparison arr1>=arr2
[[ True  True False]
 [False False False]
 [False False False]]
Performing element-wise comparison arr1<arr2
[[False False  True]
 [ True  True  True]
 [ True  True  True]]
Performing element-wise comparison arr1<=arr2
[[False  True  True]
 [ True  True  True]
 [ True  True  True]]


In [23]:
#Q12

import numpy as np

arr = np.ones((10,10))
arr[1:-1, 1:-1] = 0
print(arr)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]
